services:
  frontend:
    build:
      context: ./application
    container_name: inventory_frontend
    ports:
      - "80:80"
    depends_on:
      - server
      - minio

  server:
    build:
      context: ./server
    container_name: inventory_server

    extra_hosts:
      - "host.docker.internal:host-gateway"

    environment:
      NODE_ENV: production
      DB_HOST: host.docker.internal
      DB_PORT: 5432

    ports:
      - "3001:3001"

    env_file:
      - ./server/.env.development

    depends_on:
      - minio

  minio:
    image: minio/minio
    container_name: inventory_minio
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      MINIO_ROOT_USER: admin
      MINIO_ROOT_PASSWORD: password123
      MINIO_SERVER_URL: "http://localhost:9000"
    volumes:
      - minio_data:/data
    command: server /data --console-address ":9001"

volumes:
  minio_data:
